# Bind to all interfaces inside Docker
bind 0.0.0.0

# Default port
port 6379

# Password — change this to something strong
requirepass mansuurtech101!

# Persistence — save to disk every 60 seconds if at least 1 key changed
save 60 1

# Where to store the dump file
dir /data
dbfilename dump.rdb

# Max memory (adjust to your machine — 256mb is fine for dev)
maxmemory 256mb

# When max memory is hit, remove least recently used keys
maxmemory-policy allkeys-lru

# How many databases (we use 0 and 1 in our setup)
databases 16

# Log level
loglevel notice
